### ISSUE TITLE
Caller interface error

### ISSUE THREAD

**Issue by tobz-nz** [BeatSwitch/lock-laravel#14]
I'm getting this error:

```
Argument 1 passed to BeatSwitch\Lock\Manager::caller() must be an instance of BeatSwitch\Lock\Callers\Caller, instance of Fusion\Model\User given, ...
```
I have not implemented the Caller interface on my user model - as it was not specified as required to do so. Is there something missing from the docs around this?

**Comment by tobz-nz** [comment]
... erm.. ok, it just started working for no apparent reason.

**Comment by driesvints** [comment]
Hey @tobz-nz, 

You _are_ required to implement the caller interface on every entity which should be able to check permissions.

Did you eventually implement it on your User model?

**Comment by tobz-nz** [comment]
Yes; I did. Would be nice if the docs mentioned this requirement though.

**Comment by driesvints** [comment]
The documentation for Lock tells you this: https://github.com/BeatSwitch/lock#implementing-the-caller-contract

If this isn't clear then please let me know how to improve it :)

**Comment by tobz-nz** [comment]
Mentioning it on the lock-laravel install/setup section of the readme would be useful in my opinion.
It has evey other part of the setup but fails to mention implementing the Caller interface.

**Comment by driesvints** [comment]
Hmm, ok I agree with you. I'll update the install instructions to make sure people check the Lock documentation as well for further setup.

Thanks for your feedback!
