### ISSUE TITLE
Auth user does not have a valid Lock instance.

### ISSUE THREAD

**Issue by gerob** [BeatSwitch/lock-laravel#21]
Great package here. However I am unsure where to set the Lock instance on my User. 

Here's what I have.

Using:
```
    "beatswitch/lock-laravel": "0.2.*"
```

```
<?php namespace GerobLee;

use BeatSwitch\Lock\Callers\Caller;
use BeatSwitch\Lock\LockAware;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, Caller {

	use Authenticatable, CanResetPassword, LockAware;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

    public $timestamps = ['activated_at'];

	/**
	 * The type of caller
	 *
	 * @return string
	 */
	public function getCallerType()
	{
		return $this->table;
	}

	/**
	 * The unique ID to identify the caller with
	 *
	 * @return int
	 */
	public function getCallerId()
	{
		return $this->id;
	}

	/**
	 * The caller's roles
	 *
	 * @return array
	 */
	public function getCallerRoles()
	{
		return ['admin', 'user'];
	}

}
```

UserManagementController:
```
<?php namespace GerobLee\Http\Controllers;

use BeatSwitch\Lock\Manager;
use GerobLee\User;
use Input;
use Redirect;

class UserManagementController extends Controller
{
    /**
     * @var Manager
     */
    protected $lockManager;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Manager $lockManager)
    {
        $this->middleware('auth');
        $this->lockManager = $lockManager;
    }

    public function togglePermission()
    {
        $userId = Input::get('user_id');
        $action = Input::get('action');
        $resource = Input::get('resource');

        $user = User::findOrFail($userId);

        $this->lockManager->caller($user)->toggle($action, $resource);

        return Redirect::route('home');
    }
}
```

I can post to this route and it sets the record in the database, however in the view when I try:

```
	@if(Auth::user()->can('create', 'users'))
		<p>User can create other users!</p>
	@endif
```

This throws the error:
```
ErrorException in LockAware.php line 144:
Please set a valid lock instance on this class before attempting to use it. (View: /home/vagrant/sites/geroblee/resources/views/home.blade.php)
```

I feel like I am just missing something simple but it's been a long week. :)

Thanks for any help you can offer!
Gerob

**Comment by misterdesign** [comment]
Same for me ... some news about it?

**Comment by gerob** [comment]
I couldn't get it working without feeling like I was being quite hacky, so I went with Entrust for Laravel 5 instead. All good there so far.

**Comment by minkbear** [comment]
I have the same problem but no solution right now.

**Comment by driesvints** [comment]
I'm just gonna be honest with you guys. I don't have the time atm to look into this and probably won't have for the upcoming weeks. If anyone can take the time to figure this out, that'd be great :confused:

**Comment by msvitok** [comment]
I think the problem is that when closure in `bootstrapAuthedUserLock()` method is executed before session data is loaded and call `$app['auth']->user()` returns null (internally it fails in Guard#user() method, `$id = $this->session->get($this->getName());`). 

Session data is loaded in `Illuminate\Session\Middleware\StartSession` middleware, so we need to delay closure callback after this event. The most natural way to me is to create a custom middleware that is invoked after `StartSession` and let it load all permissions - so move `bootstrapPermissions()` invocation from `boot()` to this middleware. 
I made a pull request with this change, see https://github.com/BeatSwitch/lock-laravel/pull/31

Unfortunately this change introduces new requirement - to add BeatSwitch\Lock\Integrations\Laravel\Middleware\LockPermissions entry to $middleware array in Kernel class. Probably the documentation should be also updated.

Does this make sense? Can you validate the pull request please? 
Thanks!

**Comment by EtHVjDB7tc3K** [comment]
Is this package being actively maintained? Has the above mentioned pull request been validated? Cheers.

**Comment by driesvints** [comment]
No, I'm not maintaining the package for now. Other obligations I'm afraid.

**Comment by gerob** [comment]
Closing issue since it's not being maintained and there are other options out there with maintainers. @driesvints Thanks for releasing this, I understand how hard it can be to maintain a package especially when you stop using it yourself.

**Comment by driesvints** [comment]
The thing is, we're still using Lock at BeatSwitch but the current functionality provides enough value for us. I'm definitely going to pick development at some point, just don't have the time atm.

I knows this sucks for a lot of people and I'm really sorry. I just have to put my time and effort atm into things which are more important to me.
