### ISSUE TITLE
L5.1 ?

### ISSUE THREAD

**Issue by xLink** [BeatSwitch/lock-laravel#26]
Is there going to be any work made to get this working for 5.1? Totally not sure if the version bump will just make it work, or if it will be a little more involved..

**Comment by driesvints** [comment]
I've put development for Lock on hold for the time being because of other priorities. But you're always free to send in a PR to fix any potential issues.

**Comment by xLink** [comment]
https://github.com/BeatSwitch/lock-laravel/pull/27
:D
