### ISSUE TITLE
Question: Assigning role(s) to a particular user for database driver.

### ISSUE THREAD

**Issue by ziming** [BeatSwitch/lock-laravel#30]
Apologies for this seemingly simple question. Is there a way for me to assign role(s) to a particular user using the database driver? I checked out the docs and it seems to me that to assign roles to a class, I had to implement the Caller interface for my User class. However, I would like to have different role(s) for different users instead of everyone in the class getting the same role.

Is there a good way to achieve this without creating more classes? Thank you.

**Comment by driesvints** [comment]
Assigning roles is a task for your app, not for Lock. Lock merely handles permission handling and not the logic of assigning roles to callers. You provide who the caller is and what roles he has and Lock will determine what the permissions are for that caller.

Thanks for asking though and never be afraid to ask questions! :-)
