### ISSUE TITLE
Create branch for Laravel 4.2 support

### ISSUE THREAD

**Issue by nikita240** [BeatSwitch/lock-laravel#46]
Can we create a new branch for Laravel 4.2 bugfixes? 

I have a project on 4.2 that's using lock-laravel v0.1.3

Would like to PR a bug fix. It'd be nice to create a 4.2 support branch. 

Thanks!

**Comment by driesvints** [comment]
Heya, sorry but 4.2 is no longer supported and this package isn't maintained anymore. I suggest you fork the package and use an inline alias to pull in your bug fix: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

Sorry about that. Good luck!
