### ISSUE TITLE
Performance issue, lot of queries

### ISSUE THREAD

**Issue by MathieuDoyon** [BeatSwitch/lock-laravel#5]
If I use allowed() method for my user paginate listing I got a lot of queries

```$ids = Auth::user()->allowed('manage', 'scenes');```

![capture d ecran 2015-01-08 11 05 01](https://cloud.githubusercontent.com/assets/1854511/5665416/4279e038-9726-11e4-8918-2cb53f13fe27.png)

**Comment by MathieuDoyon** [comment]
A single ```Auth::user()->can('manage', 'scenes')``` ```$manager->alias('manage', ['create', 'read', 'update', 'delete']);```

give me 8 queries
```
select * from `lock_permissions` where `caller_type` = 'users' and `caller_id` = '6'
select * from `lock_permissions` where `caller_type` = 'users' and `caller_id` = '6'
select * from `lock_permissions` where `role` = 'guest'
select * from `lock_permissions` where `role` = 'guest'
select * from `lock_permissions` where `role` = 'user'
select * from `lock_permissions` where `role` = 'user'
select * from `lock_permissions` where `role` = 'member'
select * from `lock_permissions` where `role` = 'member'
```

**Comment by MathieuDoyon** [comment]
I fixed that with pull #6 (optimizing performance)

**Comment by driesvints** [comment]
This should now be fixed with https://github.com/BeatSwitch/lock-laravel/commit/ae98f7b77a1b87ad96c0c286a1991df427cccc80

I'll tag a new patch release in a bit. Can you perhaps test this out? Thanks!

**Comment by driesvints** [comment]
Just tagged 0.1.2. Please let me know if this has improved.
